import type {TopicId} from '../topics.ts';

export const explorations: Record<TopicId, {idea: string; tryIt: string; notice: string; model: string}> = {
  'inclined-plane': {
    idea: 'A ramp makes lifting easier by giving you a longer path, like rolling a suitcase up a slope.',
    tryIt: 'Make the ramp longer. What happens to the push?',
    notice: 'The longer ramp needs a smaller push. You push farther to reach the same height, so the total lifting work stays the same.',
    model: 'The readings assume steady movement without friction. The repeating animation shows the paths; it does not calculate the extra push needed to speed up a real load.',
  },
  levers: {
    idea: 'A seesaw shows why pushing farther from a pivot can help lift something heavy.',
    tryIt: 'Choose First, then move the pivot toward the load.',
    notice: 'A longer effort arm needs less force but moves farther. Second always helps with force; Third gives the load more travel instead.',
    model: 'The bar stays perfectly stiff, its own weight is ignored, and the pivot has no friction. The animation prescribes the tilt rather than predicting movement from forces.',
  },
  'wheel-and-axle': {
    idea: 'A wide handle makes a screwdriver easier to turn. A wheel and axle uses the same advantage to pull a rope.',
    tryIt: 'Make the wheel bigger. Does lifting get easier?',
    notice: 'Doubling the wheel radius halves the hand force needed for the same load. Your hand travels twice as far each turn.',
    model: 'The wheel and axle turn together, the rope does not stretch, and friction is ignored. Each turn winds the same length of rope onto the unchanged axle.',
  },
  'gears-and-belts': {
    idea: 'Bicycle gears trade turning speed for turning strength. Different wheel sizes make the same trade here.',
    tryIt: 'Make the driven wheel bigger. Watch its turning speed.',
    notice: 'The larger driven wheel turns more slowly but gives a stronger twist. Touching gears turn opposite ways; this uncrossed belt turns both the same way.',
    model: 'The speed ratio assumes a perfect link with no slipping or energy loss. Real belts can slip, and real gear teeth and bearings add friction.',
  },
  'cams-and-cranks': {
    idea: 'A turning wheel can make something move back and forth, as a motor does in windshield wipers.',
    tryIt: 'Increase Throw. Does the piston travel farther?',
    notice: 'Moving the crank pin farther from the center makes a longer piston stroke. The cam also lifts its follower farther as its offset grows.',
    model: 'This cam is a simple off-center circle. The rod stays rigid and the follower stays in contact; the animation does not predict wear, friction, or bouncing at high speed.',
  },
  pulleys: {
    idea: 'Sharing a load among several rope strands makes lifting easier, like the ropes used on a crane.',
    tryIt: 'Add supporting strands. Compare the pull and rope travel.',
    notice: 'Four supporting strands each carry a quarter of the load. You need a quarter of the pull, but must haul four times as much rope.',
    model: 'The rope has no weight or stretch, and every pulley turns without friction. The moving pulley frame adds no weight to the load in these readings.',
  },
  screws: {
    idea: 'A screw wraps a ramp around a shaft, turning many small turns into a strong push, as in a clamp.',
    tryIt: 'Increase Thread pitch. Watch the nut move each turn.',
    notice: 'A wider pitch moves the nut farther each turn but reduces the ideal force gain. Double threads double the travel again at the same pitch.',
    model: 'Force gain ignores friction. The holding verdict uses one assumed friction angle; real holding depends on materials, lubrication, thread shape, and vibration. The animation repeats a chosen stroke.',
  },
  'rotating-wheels': {
    idea: 'A spinning toy top resists changes to its direction. A spinning wheel also stores energy that can be used later.',
    tryIt: 'Double Spin rate from 30 to 60. Compare the stored energy.',
    notice: 'Twice the spin rate stores four times the energy and needs four times the inward rim force. In Gyroscope, faster spin makes the axis circle more slowly.',
    model: 'Wheel size and mass stay fixed. The gyroscope assumes steady circling under a fixed turning force. Motion is slowed for viewing; bearing friction and wobbling are left out.',
  },
  springs: {
    idea: 'A spring gives under a push and pushes back, helping a bicycle ride over bumps.',
    tryIt: 'Double Stiffness from 10 to 20. How far does the load sink?',
    notice: 'The same load bends a spring with twice the stiffness only half as far. Different spring shapes can provide the same push at the load.',
    model: 'Spring force grows evenly with deflection. The load is applied gradually; bouncing, energy loss, and permanent bending are not calculated. Torsion stiffness is measured at the arm tip.',
  },
  friction: {
    idea: 'Friction helps shoes grip the ground and bicycle brakes slow a wheel. It also makes sliding harder.',
    tryIt: 'Increase Grip before sliding. How steep can the plank go?',
    notice: 'More grip lets the block stay put on a steeper slope. Once it slides, friction is smaller here, and sliding turns movement energy into heat.',
    model: 'This dry-surface model sets sliding friction to 80% of starting friction. That ratio varies in real materials. Sliding and braking animations use chosen timing rather than calculated stopping times.',
  },
  floating: {
    idea: 'A boat floats by pushing aside water whose weight matches its own. Air inside helps keep its average density low.',
    tryIt: 'Try densities of 700, 1000 and 1200. Does the hull float?',
    notice: 'A denser hull sits deeper. At water’s density it balances when fully submerged; above that, even all the displaced water cannot support its weight.',
    model: 'The hull has straight sides in still fresh water. Water entering the hull and waves are not calculated. Sinking uses a chosen animation path, not a predicted sinking speed.',
  },
  flying: {
    idea: 'A wing pushes air downward, and the air pushes the wing upward. That upward force helps an airplane fly.',
    tryIt: 'Tilt the wing from 6° to 20°. Does lift always grow?',
    notice: 'Tilting first increases lift, then lift falls after the wing stalls. In this example, flaps add lift but also drag and reach stall at a smaller angle.',
    model: 'Air speed and wing area stay fixed. Lift and drag use simple teaching rules. Airflow lines are a schematic drawing, not measured airflow or a calculation of air moving around the wing.',
  },
  'pressure-power': {
    idea: 'Trapped liquid can pass a push to a wider piston, helping a small handle lift a car.',
    tryIt: 'Double the piston width. Compare the force and travel.',
    notice: 'Twice the width gives four times the piston area: more force, less travel. Gas squeezes first, so less of the handle’s movement reaches the load.',
    model: 'The hand force stays fixed. Liquid cannot compress here; gas compresses at constant temperature. Leaks, friction, and pressure travel time are ignored, and the stroke follows a chosen animation cycle.',
  },
  'exploiting-heat': {
    idea: 'An engine can use heat flowing from hot to cold. A refrigerator needs power to carry heat the other way.',
    tryIt: 'Widen the temperature gap. Compare Engine and Refrigerator.',
    notice: 'A bigger temperature gap lets an ideal engine turn more heat into work. A refrigerator needs more work to move heat across that bigger gap.',
    model: 'These are best possible limits between two fixed temperatures. Real machines waste more energy. The piston and moving dots illustrate the exchange; they do not simulate a particular engine or refrigerator.',
  },
  'nuclear-power': {
    idea: 'Splitting atoms releases heat. In a power station, control rods catch some of the tiny particles that keep the splitting going.',
    tryIt: 'Try rods at 0%, 25% and 100%. Watch the chain reaction.',
    notice: 'With rods farther in, fewer particles continue the chain. This model grows below 25% insertion, stays steady at 25%, and shrinks above it.',
    model: 'Dots stand for groups of neutrons. Each cycle represents 50 generations, not real seconds. The model leaves out delayed neutrons, temperature changes, fuel changes, and heat remaining after shutdown.',
  },
  'light-and-images': {
    idea: 'A lens or a mirror bends light to make an image. Moving the object changes where that image appears and how large it looks, and swapping the element changes what kind of image is possible at all.',
    tryIt: 'On the converging lens try 250, 100 and 50 mm. Then put the diverging lens in its place and run the whole slider: nothing you do makes a real image. Then the flat mirror, which never changes the size of anything.',
    notice: 'The two elements that gather light make an upside-down image a screen can catch, but only outside the focal distance; inside it the image turns upright and virtual. The two that spread light have no outside: they are virtual, upright and smaller at every setting. That is the sign of the focal length doing all the work.',
    model: 'Five ideal elements, all of one aperture and one focal length of 100 mm, positive for the two that gather and negative for the two that spread. Color differences and imperfect focus are ignored. With the object at 100 mm from a gathering element the rays leave parallel; images beyond the bench are omitted but still reported.',
  },
  photography: {
    idea: 'A camera opening controls how much light enters, like opening a curtain wider. It also changes how much of a scene looks sharp.',
    tryIt: 'Change f/4 to f/8. What happens to shutter time?',
    notice: 'The smaller opening lets in less light but makes a wider range look sharp. Higher ISO shortens the required exposure time without changing that sharp range.',
    model: 'Lighting, lens, and subject distance stay fixed. Sharpness uses one blur threshold. The shutter animation is slowed and does not match the exposure reading; sensor noise is not drawn.',
  },
  printing: {
    idea: 'Printed pictures use tiny dots of ink. From far enough away, your eyes blend the dots and white paper into shades.',
    tryIt: 'Increase Screen ruling. Can you still see individual dots?',
    notice: 'More lines pack smaller dots closer together. The covered fraction stays the same, so the average shade stays similar. Black only removes the colored inks.',
    model: 'Dots are enlarged for inspection. Ink coverage stays fixed as spacing changes. Color mixing is approximate; paper texture, ink spreading, and differences between screens and printed pages are left out.',
  },
  'sound-and-music': {
    idea: 'Shortening a guitar string raises its note. Shortening the vibrating air inside a pipe does something similar.',
    tryIt: 'Halve Working length from 600 to 300 mm. Does frequency double?',
    notice: 'Half the working length doubles the frequency, giving a higher note. At the same length, a stopped pipe has half an open pipe’s frequency.',
    model: 'Vibrations are slowed for viewing. Air-wave curves are diagrams: the air moves back and forth along the direction sound travels, not sideways along the curve. String tension and thickness stay fixed; pipe calculations ignore end corrections.',
  },
  telecommunications: {
    idea: 'Radio carries a message by changing a repeating wave. AM changes its height; FM changes how closely its peaks are spaced.',
    tryIt: 'Increase Carrier frequency. What happens to antenna length?',
    notice: 'Higher frequency means shorter waves and a shorter matching antenna. AM varies the wave’s height; FM varies the spacing of its peaks.',
    model: 'Wave traces are slowed and the displayed frequency range is compressed. Antenna readings assume an ideal quarter-wave antenna. Terrain, interference, receiver behavior, and real transmission range are not simulated.',
  },
  electricity: {
    idea: 'A battery pushes charge round a loop, the way a pump pushes water round a pipe.',
    tryIt: 'Lower the resistance from 40 Ω to 6 Ω. Watch the lamp.',
    notice: 'Less resistance lets more current through, so the lamp burns brighter and the supply works harder. Adding a second branch beside the first doubles the current the supply must deliver.',
    model: 'The supply voltage is fixed and the wires are treated as perfect. Real cells sag under load, and resistance changes as things heat. The moving beads are drawn far faster than electrons actually drift, and the readout gives the real drift speed.',
  },
  magnetism: {
    idea: 'Every electric current is wrapped in a magnetic field. Wind the wire into a coil and the fields add up.',
    tryIt: 'Switch the core from air to iron at the same current.',
    notice: 'The same current in the same coil makes a far stronger field with iron inside it. The compass needle turns to follow the field wherever it stands.',
    model: 'The field figure is the long coil formula, turns per meter times current; the compass angle uses the exact finite coil field on its axis, added to an assumed 50 microtesla of the earth\u2019s field across the bench. The iron is a fixed multiplier, and a real core stops multiplying once its domains are lined up. The field lines are dipole shaped, drawn to show what a field looks like rather than computed for this coil.',
  },
  'electric-motors': {
    idea: 'A wire carrying current across a magnet is shoved sideways. Hinge a loop of it and the loop turns.',
    tryIt: 'Switch from With commutator to Plain slip rings and watch.',
    notice: 'With the commutator the coil keeps turning the same way. Without it the coil swings to the upright position and settles there, because past that point the same current pushes it back.',
    model: 'The field in the gap is treated as even and fixed. Friction, the mass of the coil and sparking at the brushes are left out, and the turning is animated at a chosen rate rather than predicted from the torque.',
  },
  'generators-and-transformers': {
    idea: 'A motor run backward is a generator. Turn a coil in a field and a voltage appears at its ends.',
    tryIt: 'In Transformer, set the secondary to 100 turns, then 2,000.',
    notice: 'Fewer turns than the primary means fewer volts and more amps; more turns means the reverse. The power through is the same either way, which is why raising the voltage cuts what the line wastes.',
    model: 'The transformer is ideal: no leakage, no core loss, no winding resistance. The generator assumes a steady turning rate in an even field, which is what makes its output a sine and lets the steady value be the peak over the square root of two. The coil turns about 140 times slower than the 50 a second the readout names, or it would be a blur.',
  },
  'sensors-and-detectors': {
    idea: 'To answer to the world, a machine needs something whose electrical behavior changes with it.',
    tryIt: 'Compare Thermistor and Platinum at 25 °C and at 150 °C.',
    notice: 'The thermistor changes far more per degree, but by different amounts at different temperatures. Platinum changes less and, in this straight line model, by the same amount everywhere, which is what makes it trustworthy.',
    model: 'The thermistor uses the beta model, fitted over a limited range, and is the kind whose resistance falls as it warms. Platinum uses a straight line, which the real curve bends slightly away from, and the thermocouple a fixed 41 microvolts per kelvin. The meter is assumed to draw no current, and self heating, wiring resistance and drift in the supply are ignored.',
  },
  'making-bits': {
    idea: 'To store a sound as numbers, measure its height over and over and round each measurement.',
    tryIt: 'Drop the sample rate below 24 thousand a second.',
    notice: 'Sampled at more than twice the tone, the samples pin it down. At exactly twice, they cannot. Below that, the tone folds into a lower one that nothing later can undo. More bits make the rounding steps finer, and rounding always loses a little.',
    model: 'One steady tone at a fixed frequency. The staircase is what gets stored, not what comes back out: a real converter filters it back toward a smooth wave. Real systems also filter the input before sampling, which is what prevents the fold.',
  },
  'storing-bits': {
    idea: 'A disc holds data in rings and finds it by moving a head there and waiting for it to come round.',
    tryIt: 'Change the spin rate. Then change the track density.',
    notice: 'Packing tracks closer multiplies the capacity and does nothing at all for the wait. Only spinning faster shortens it, and even 15,000 rpm still averages two milliseconds.',
    model: 'Every track carries the same number of sectors, which is the simple scheme; real drives put more on the outer tracks. Seek time, caching and error correction are left out. The finest setting here is still far coarser than a real drive.',
  },
  'processing-bits': {
    idea: 'Switches wired so that one depends on others can add. Enough of them can do anything.',
    tryIt: 'Widen the word from 4 bits to 16 and watch the carry.',
    notice: 'Each extra bit doubles how many different values the machine can hold. With a ripple carry the wait grows in step with the width, because each column must wait for the one below it.',
    model: 'Two gate delays per stage, and one nanosecond per gate. Both are model figures, not measurements of any real silicon. Lookahead is modeled as a tree, which is the shape of the usual arrangement.',
  },
  'sending-bits': {
    idea: 'How fast a channel can carry information is set by its width and by how much noise is in it.',
    tryIt: 'Raise the signal to noise from 10 dB to 40 dB.',
    notice: 'Each 3 dB, a doubling of signal power, buys about one more bit per second for each hertz of bandwidth, and no more. Widening the channel helps far more than shouting louder.',
    model: 'This is Shannon\u2019s limit for a channel of fixed bandwidth carrying limited power against steady random noise. Real links run below it and carry overheads. The settings here span eight decades of capacity, so the blocks move at the logarithm of it rather than in proportion, and the readout carries the figure.',
  },
  'using-bits': {
    idea: 'A picture is a grid of dots, each made of a red, a green and a blue light too small to see separately.',
    tryIt: 'Set the depth to 2 bits, then to 8, and look at the ramp.',
    notice: 'Too few bits and a smooth gradient breaks into visible bands. More pixels and more bits both look better and both cost data, and the raw stream is far more than any link carries.',
    model: 'These are uncompressed figures. A display cable usually carries them as they are and a network connection usually does not, though neither is a rule: studios move uncompressed video over networks, and display cables compress when the panel outruns the wire. The panel draws one fortieth of the picture so the grid can keep answering to the slider, and the readout gives the count for the whole of it. The cost bar runs on the logarithm of the size, across the three decades the slider covers, so its length is an order of magnitude and not a proportion.',
  },
};
